#
#      Copyright (c) 2020 World Wide Technology, LLC.
#      All rights reserved.
#
#      author: joel.king@wwt.com GitHub/GitLab @joelwking
#
#      references:
#          https://gitlab.com/gitlab-org/gitlab/-/issues/37470
#          https://about.gitlab.com/blog/2019/07/01/using-ansible-and-gitlab-as-infrastructure-for-code/
#
#      note: additional packages can be installed by adding them to the 'script' commands, e.g.
#            # - pip install ansible-lint

image: joelwking/ansible:1.0

stages:
  - lint
  - secondary

ansible_linting:
  variables:
    GIT_SSL_NO_VERIFY: "True"
  stage: lint
  script:
    - ansible --version
    - ansible-galaxy collection install cisco.aci
    - ansible-lint --version
    - ansible-lint demos/engine/playbooks/sample.yml

step_two:
  variables:
    GIT_SSL_NO_VERIFY: "True"
  stage: secondary
  script:
    - dig wwt.com
