#!/usr/bin/ansible-playbook
#
#      Copyright (c) 2020 World Wide Technology
#      All rights reserved.
#      author: @joelwking
#
#      This playbook creates credentials when using signature based authentication with the APIC
#      It relies on a internal WWT role, which is not publically assessable.
#
#      Requirements: download the role by cloning into ./roles/
#
#      usage: ./dc_coi_apic_credentials.yml -e "fabric=sandboxapicdc.cisco.com pw_file=devnet"
#
#      Note: the password file should look similar to:
#
#      apic:
#        username: kingjoe
#        password: changeme123,
#
---
- name: Run the credential role against the Cisco ACI fabric
  hosts: '{{ fabric | default("aci-demo.sandbox.wwtatc.local") }}'
  connection: local
  gather_facts: no

  vars:
    aci_credentials:
      filename: '{{ pw_file | default("cisco_dc_coi") }}'  # see ./files/cisco_dc_coi.yml for example
      seconds: 15                                          # allows for delay after cert creation
      validate_certs: false

  roles:
    - ansible-aci-credentials

  tasks:
    - name: debug
      debug:
        msg:  "{{ item }}"
      loop:
        - "{{ lookup('file', '{{ playbook_dir }}/files/{{ apic.username }}.crt') }}"
        - "{{ lookup('file', '{{ playbook_dir }}/files/{{ apic.username }}.key') }}"

    - name: Query all tenants, verify we can use signature based authentication
      cisco.aci.aci_tenant:
        host: "{{ inventory_hostname }}"
        username: '{{ apic.username }}'
        private_key: "{{ lookup('file', '{{ playbook_dir }}/files/{{ apic.username }}.key') }}"
        validate_certs: false
        state: query
      register: tenants
